# Generated by Django 3.0 on 2021-11-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='payment_statuc',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
