# Generated by Django 3.0 on 2021-11-24 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_cart_payment_statuc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='payment_statuc',
            new_name='payment_status',
        ),
    ]
